name: YOLO
server:
  cut-layer: a #or a, b, c, d
  clients:
    - 1
    - 1
  model: yolo11n
  batch-frame: 30
#rabbit:
  # address: 192.168.101.234
  #address: 127.0.0.1
  #username: guest
  #password: guest 
  #virtual-host: /

data: video.mp4
log-path: .
control-count: 10
debug-mode: False
compress:
  enable: True
  num_bit: 8
cal_map:
  enable: False
  create_label: False

redis:
  enable: True
  address: 127.0.0.1
  port: 6379
  password: null